name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14-bullseye
    steps:
      - name: log node version
        run: node -v

      - name: step with docker
        uses: docker://node:18-buster
        with:
          entrypoint: '/bin/echo'
          args: 'hello world'

  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: scottyfullstack/basic-rest-api:latest
        ports:
          - 8000:8000
      postgres:
        image: postgres:12
        ports: 
          - 5432:5432
    steps:
      - name: POST product
        run: curl --location --request POST 'localhost:8000/api/' --form 'title="Apple"' --form 'description="fruit"' --form 'price="$0.99"'

      - name: GET product
        run: curl --location --request GET 'localhost:8000/api/'

    # container: 
    #   image: node:18-alpine3.15
      # ports:
      # volumes:
      # env:
      # options: --cpus 1 --host
    # steps:
    #   - name: Log node version
    #     run: |
    #       node -v
    #       cat /etc/os-release

    #       # curl localhost:8000/api --location --request GET 'localhost:8000/api'